// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxYo_s--147hrSHpPDutT3QXq5RvLxFSM',
    appId: '1:169406025876:web:1cf4a189a34121184fe481',
    messagingSenderId: '169406025876',
    projectId: 'chat-app-e82b8',
    authDomain: 'chat-app-e82b8.firebaseapp.com',
    storageBucket: 'chat-app-e82b8.appspot.com',
    measurementId: 'G-VW04VDD9YP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR4nsCI7XSBrBLy5YbREwhDG379ijzD2E',
    appId: '1:169406025876:android:d51d412beee876724fe481',
    messagingSenderId: '169406025876',
    projectId: 'chat-app-e82b8',
    storageBucket: 'chat-app-e82b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsmvSK4_5X7hkRteZixiNcjIx_nzKIRy4',
    appId: '1:169406025876:ios:ed1b6f5e615ca27e4fe481',
    messagingSenderId: '169406025876',
    projectId: 'chat-app-e82b8',
    storageBucket: 'chat-app-e82b8.appspot.com',
    iosBundleId: 'com.example.interconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsmvSK4_5X7hkRteZixiNcjIx_nzKIRy4',
    appId: '1:169406025876:ios:ed1b6f5e615ca27e4fe481',
    messagingSenderId: '169406025876',
    projectId: 'chat-app-e82b8',
    storageBucket: 'chat-app-e82b8.appspot.com',
    iosBundleId: 'com.example.interconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxYo_s--147hrSHpPDutT3QXq5RvLxFSM',
    appId: '1:169406025876:web:4ed64302431be5724fe481',
    messagingSenderId: '169406025876',
    projectId: 'chat-app-e82b8',
    authDomain: 'chat-app-e82b8.firebaseapp.com',
    storageBucket: 'chat-app-e82b8.appspot.com',
    measurementId: 'G-MEW4Y9Z2YX',
  );
}
